version: '3.8'
services:
  git-tracking:
    container_name: 'push-to-bot'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '5555:5555'
