version: '3.8'
services:
  git-alert:
    container_name: 'git-alert'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3333:8080'
